### ISSUE TITLE
Run docker_build.sh issue

### ISSUE THREAD

**Issue by zhangnaiqian** [RUB-SysSec/gadget_synthesis#1]
Dear author, I am using your gadget_synthesis tool, when running docker_build.sh script, I got the following error message: 

Step 7/24 : RUN locale-gen en_US.UTF-8
 ---> Using cache
 ---> 4df8762547ce
Step 8/24 : ARG USER_UID=1000
 ---> Using cache
 ---> 9c139717c8ae
Step 9/24 : ARG USER_GID=1000
 ---> Using cache
 ---> 388f924f10a2
Step 10/24 : RUN echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
 ---> Using cache
 ---> d3a8392e9011
Step 11/24 : WORKDIR /tmp
 ---> Using cache
 ---> c3faa354cc6d
Step 12/24 : RUN update-locale LANG=en_US.UTF-8
 ---> Using cache
 ---> 79f5902085c0
Step 13/24 : ENV LANG=en_US.UTF-8
 ---> Using cache
 ---> 3dbae1514b17
Step 14/24 : RUN groupadd -g ${USER_GID} user
 ---> Running in eb0a063eed81
groupadd: GID '0' already exists
The command '/bin/sh -c groupadd -g ${USER_GID} user' returned a non-zero code: 4

I tried to change the GID value, but it didn't work.
Any tricks here or am I doing something wrong for this step?

Thank you!

**Comment by mu00d8** [comment]
Hi there,

I'm not sure how the GID 0 ends up there, especially as USER_GID is set to 1000 in step 9. Is the environment variable USER_GID set on your system? Can you modify the respective line in the dockerfile to `RUN groupadd -g 1000 user` and re-run the script as follows: `./docker_build.sh --no-cache`?

If that doesn't help, it would be good to know some more details like are you running this script as root (you shouldn't need to) or which OS are you using?

**Comment by zhangnaiqian** [comment]
'USER_GID' is not the environment variable on my system. This method works! Thank you very much for your help!
